# Generated by Django 4.1.1 on 2022-09-13 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_category_slug_alter_ad_description_alter_ad_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'The field must contain at least 10 characters')]),
        ),
    ]
